name: Run Tests on PR to Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore api

      - name: Build project
        run: dotnet build api --no-restore --configuration Release

      - name: Run tests
        run: dotnet test api --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"